version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11

    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Creating application zip"
      - zip -r app.zip .

      - echo "Uploading encrypted artifact to S3"

      - aws s3 cp app.zip s3://aws-project-577267184066/artifacts/app.zip --sse aws:kms --sse-kms-key-id arn:aws:kms:us-east-1:577267184066:key/785928ca-2c9e-4c79-933e-2318ae9c3ff4

artifacts:
  files:
    - app.zip
